# Generated by Django 4.2.16 on 2025-01-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='eircode',
            new_name='default_eircode',
        ),
    ]
