# Generated by Django 4.2.16 on 2025-01-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eircode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
