# Generated by Django 4.2.16 on 2025-01-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dietary Category',
                'verbose_name_plural': 'Dietary Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name in lowercase, separated by underscores.', max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('short_widget_name', models.CharField(max_length=255)),
                ('energy_kj', models.DecimalField(decimal_places=2, max_digits=7)),
                ('energy_kcal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugars', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cooking_process', models.IntegerField(choices=[(1, 'baking'), (2, 'frying'), (3, 'frying or baking')], default=1)),
                ('allergens', models.CharField(help_text='Enter allergens separated by commas. Example: Dairy, Eggs, Nuts', max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('best_seller', models.BooleanField(default=False)),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='products/large/')),
                ('image_widget', models.ImageField(blank=True, null=True, upload_to='products/widgets/')),
                ('dietary_categories', models.ManyToManyField(related_name='products', to='products.dietarycategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('offer', models.IntegerField(choices=[(1, 'No Offer'), (2, 'Discount')], default=1)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date'],
            },
        ),
    ]
