# Generated by Django 4.2.16 on 2025-01-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['sale_price'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
    ]
