# Generated by Django 4.2.16 on 2024-12-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sodium',
            new_name='salt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_large_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_widget_url',
        ),
    ]
