# Generated by Django 4.2.16 on 2024-12-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_sodium_product_salt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
