# Generated by Django 4.2.16 on 2024-12-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_batch_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='offer',
            field=models.IntegerField(choices=[(1, 'No Offer'), (2, 'Discount')], default=1),
        ),
    ]
