# Generated by Django 4.2.16 on 2025-01-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_batch_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='cooking_process',
            field=models.IntegerField(choices=[(1, 'baking'), (2, 'frying'), (3, 'frying or baking')], default=1),
        ),
    ]
